name: BlueHouse
favicon: null
layout_spectrum: 0.5870480167213827
typography_spectrum: 0.4180539632216096
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#609ac6'
    - '#022e64'
    - '#9bbed8'
    - '#436287'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.375
  rhythmicContrast: 0
purpose: []
